"""Конфиг."""

from arcade import color

SCREEN_WIDTH = 640
SCREEN_HEIGHT = 480
SCREEN_TITLE = "Snake — Arcade"

CELL_SIZE = 20
GRID_WIDTH = SCREEN_WIDTH // CELL_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // CELL_SIZE

SNAKE_FPS = 5

# цвета
BG_COLOR = color.BLACK
SNAKE_HEAD_COLOR = color.APPLE_GREEN
SNAKE_TAIL_COLOR = color.DARK_GREEN
FOOD_COLOR = color.RED
